kind: pipeline
name: default

steps:

- name: frontend
  image: node:15.8.0-alpine3.12
  commands:
  - ./build.sh frontend

- name: golang
  image: golang:1.16rc1-alpine3.13
  commands:
  - ./build.sh backend

- name: release
  image: plugins/gitea-release
  settings:
    base_url: https://git.quimbo.fr
    title: "Release ${DRONE_TAG}"
    files: ./homed
    api_key:
      from_secret: gitea_token
  when:
    event: tag
