debug: true
mqtt:
  broker: tcp://192.168.100.50:1883
http:
  addr: ":9091"

devices:
- name: device_1
  room: room_1
  components:
  - type: temperature
    mqtt_topic: home/devices/device_1/sensor/temperature/state
  - type: humidity
    mqtt_topic: home/devices/device_1/sensor/humidity/state
  - type: wifi_signal
    mqtt_topic: home/devices/device_1/sensor/wifi_signal/state

- name: device_2
  room: room_2
  components:
  - type: tuya_trv
    state_topic: zigbee2mqtt/device_2
    command_topic: zigbee2mqtt/device_2/set/current_heating_setpoint
