debug: true
dev: true
fake_home: true
data_path: ./data
mqtt:
  broker: tcp://127.0.0.1:1883
http:
  addr: ":9091"

temperature_control: &temperature_control
  enabled: true
  # Hysteresis is used to trigger the boiler based on the current temperature.
  hysteresis: 0.3
  # Should we recalibrate the TRV based on external temperature sensors
  calibrate_trv: true
  # How much the difference of temperature should be to recalibrate a new
  # calibration
  calibration_threshold: 1
  # Max offset of temperature to recalibrate the TRV. If the calibration is
  # over this value, the calibration will be reseted to 0.
  calibration_max_offset: 15

location: &location
  latitude: 50.62955091282183
  longitude: 3.055823770700181

roller_shutter: &roller_shutter
  location: *location
  enabled: true
  # Random delay to be added to the sunrise / sunset times
  random_delay: 20

devices:
- name: homed_temperature_switch
  room: none
  components:
  - type: homed_temperature_switch
    params:
      switches:
        - homed_temperature_living_room

#############################
# Basement
#############################
- name: linky
  room: basement
  components:
  - type: generic_counter
    state_topic: zigbee2mqtt/linky/current_tier1_summ_delivered
    friendly_name: Linky HC
    hide: true
  - type: generic_counter
    state_topic: zigbee2mqtt/linky/current_tier2_summ_delivered
    friendly_name: Linky HP
    hide: true
  - type: power_meter
    state_topic: zigbee2mqtt/linky/apparent_power
    friendly_name: Linky
  - type: device_status
    state_topic: zigbee2mqtt/linky/availability

- name: shelly_boiler
  room: basement
  components:
  - type: boiler
    state_topic: home/devices/shelly_boiler/switch/relay/state
    command_topic: home/devices/shelly_boiler/switch/relay/command
    params: *temperature_control
  - type: wifi_signal
    state_topic: home/devices/shelly_boiler/sensor/wifi_signal/state
  - type: device_status
    state_topic: home/devices/shelly_boiler/status

- name: water_heater
  room: basement
  components:
  - type: binary_sensor
    state_topic: home/devices/water_heater/binary_sensor/provider_signal/state
    friendly_name: Signal of the provider
  - type: device_status
    state_topic: home/devices/water_heater/status

- name: washing_machine_switch
  room: basement
  components:
  - type: switch
    state_topic: home/devices/washing_machine/switch/relay/state
    command_topic: home/devices/washing_machine/switch/relay/command
    friendly_name: Washing machine
  - type: power_meter
    state_topic: home/devices/washing_machine/sensor/power/state
    friendly_name: Washing machine
  - type: device_status
    state_topic: home/devices/washing_machine/status

#############################
# Living room
#############################
- name: homed_temperature_living_room
  room: living_room
  components:
  - type: homed_temperature
    id: homed_temperature_living_room
    schedule_name: temperature_floor_0
    internal: true
    state_topic: home/homed/temperature/rooms/living_room/state
    command_topic: home/homed/temperature/rooms/living_room/command
    params: *temperature_control
    friendly_name: Living Room

- name: climate_sensor_living_room
  room: living_room
  components:
  - type: zigbee_climate_sensor
    friendly_name: Temperature Living Room
    state_topic: zigbee2mqtt/tmp_living_room
  - type: device_status
    state_topic: zigbee2mqtt/tmp_living_room/availability

- name: trv_living_room
  room: living_room
  components:
  - type: zigbee_trv
    state_topic: zigbee2mqtt/trv_living_room
    command_topic: zigbee2mqtt/trv_living_room/set
    friendly_name: Living Room
  - type: device_status
    state_topic: zigbee2mqtt/trv_living_room/availability

#############################
# Living room
#############################
- name: living_room_rs
  room: living_room
  components:
  - type: roller_shutter
    state_topic: home/devices/living_room_rs/cover/cover/position/state
    command_topic: home/devices/living_room_rs/cover/cover/command
    friendly_name: Volet salon
    params: *roller_shutter
  - type: device_status
    state_topic: home/devices/living_room_rs/status

#############################
# Stairs
#############################
- name: stairs_lights
  room: stairs
  components:
  - type: binary_light
    state_topic: home/devices/stairs_lights/switch/light_1/state
    command_topic: home/devices/stairs_lights/switch/light_1/command
    friendly_name: Floor 1
    id: light_floor_1
  - type: binary_light
    state_topic: home/devices/stairs_lights/switch/light_2/state
    command_topic: home/devices/stairs_lights/switch/light_2/command
    friendly_name: Floor 2
    id: light_floor_2
  - type: power_meter
    friendly_name: Lights floor 1
    state_topic: home/devices/stairs_lights/sensor/power_1/state
  - type: power_meter
    friendly_name: Lights floor 2
    state_topic: home/devices/stairs_lights/sensor/power_2/state
  - type: device_status
    state_topic: home/devices/stairs_lights/status

#############################
# Virtual switch
#############################

- name: virtual_switch
  room: none
  components:
  - type: virtual_switch
    state_topic: zigbee2mqtt/virtual_switch_1/action
    params:
      switches:
        - light_floor_1
        - light_floor_2
  - type: device_status
    state_topic: zigbee2mqtt/virtual_switch_1/availability

#############################
# Bathroom
#############################
- name: bathroom_fan
  room: bathroom
  components:
  - type: binary_fan
    id: bathroom_fan_switch
    state_topic: home/devices/bathroom_fan/switch/relay/state
    command_topic: home/devices/bathroom_fan/switch/relay/command
    friendly_name: VMC Bathroom
  - type: device_status
    state_topic: home/devices/bathroom_fan/status

- name: bathroom_sensor
  room: bathroom
  components:
  - type: zigbee_climate_sensor
    friendly_name: Bathroom
    id: bathroom_tmp_sensor
    state_topic: zigbee2mqtt/tmp_bathroom
  - type: device_status
    state_topic: zigbee2mqtt/tmp_bathroom/availability

- name: bathroom_humidity_controler
  room: bathroom
  components:
  - type: homed_humidity
    hide: true
    params:
      sensor: bathroom_tmp_sensor
      switch: bathroom_fan_switch
      humidity_threshold: 65

- name: bathroom_trv
  room: bathroom
  components:
  - type: binary_trv
    state_topic: zigbee2mqtt/bathroom_trv/current_heating_setpoint
    command_topic: zigbee2mqtt/bathroom_trv/set/current_heating_setpoint
    friendly_name: Bathroom TRV
  - type: device_status
    state_topic: zigbee2mqtt/bathroom_trv/availability
